apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: web-file
          mountPath: /usr/share/nginx/html/
        - name: workaround
          mountPath: /tmp/
      volumes:
        - name: web-file
          configMap:
            name: web-file
            items:
            - key: content
              path: index.html
        - name: workaround
          configMap:
            name: web-file